### ISSUE TITLE
Cannot configure accounts

### ISSUE THREAD

**Issue by afly007** [Pack3tL0ss/central-api-cli#170]
I'm trying to configure a new instance and cannot get the account to be recognized...

#~/.config/centralcli$ cencli show all
ERROR: The specified account: 'central_info' is not defined in the config.

The following accounts are defined []
The default account 'central_info' is used if no account is specified via --account parameter.

WARNING: 'central_info' is not defined in the config.  This is the default when not overriden by
--account parameter or ARUBACLI_ACCOUNT environment variable.

My config.yaml file is placed in my home directory ~/.config/centralcli and I'm using username/password...

I've tried all sorts of combinations but I cannot get it to recognize the configuration file.

**Comment by Pack3tL0ss** [comment]
Your config should look like
```yaml
central_info:
  customer_id: 123456789
  client_id: redacted
  client_secret: redacted
  base_url: https://internal-apigw.central.arubanetworks.com
  token:
    access_token: optional
    refresh_token: optional
```
Make sure the values are under `central_info` in the config.  

Also if you delete the config and update `pip3 install -U centralcli` it should ask you for the details and populate the config on first run.
